#!/bin/bash
# Vercel Deployment Checklist

echo "=================================="
echo "Vercel Deployment Checklist"
echo "=================================="

echo ""
echo "STEP 1: Set up Vercel KV (Redis)"
echo "  1. Go to: https://vercel.com/dashboard"
echo "  2. Select 'scrapee-backend' project"
echo "  3. Click 'Storage' tab"
echo "  4. Click 'Create' → 'KV'"
echo "  5. Wait for Redis to be provisioned"
echo "  6. KV_URL will be auto-added to env vars"
echo ""

echo "STEP 2: Verify environment variables"
echo "  Go to Settings → Environment Variables"
echo "  Check for: KV_URL (should start with redis://)"
echo ""

echo "STEP 3: Deploy changes"
echo "  Run these commands:"
echo "    git add -A"
echo "    git commit -m 'Add Vercel KV persistence'"
echo "    git push origin main"
echo ""
echo "  Vercel will auto-deploy and detect KV_URL"
echo ""

echo "STEP 4: Check deployment logs"
echo "  After deployment, check logs:"
echo "    vercel logs --follow"
echo ""
echo "  Look for:"
echo "    ✓ Redis connected for SQLite persistence"
echo "    ✓ Pulled SQLite database from Redis"
echo "    ✓ Pushed SQLite database to Redis"
echo ""

echo "STEP 5: Test it works"
echo "  In VSCode with MCP:"
echo "    1. Call scrape_url with https://docs.expo.dev/"
echo "    2. Wait for pages to be scraped (30 pages)"
echo "    3. Check logs - should see 'Pushed SQLite database to Redis'"
echo "    4. Call search_and_get with a query"
echo "    5. Should return results from all stored pages"
echo ""

echo "STEP 6: Verify persistence"
echo "  1. Redeploy your backend: vercel redeploy"
echo "  2. Check logs again"
echo "  3. Should see 'Pulled SQLite database from Redis'"
echo "  4. Call search again - results should still be there"
echo "  5. If you see results, persistence is working! ✅"
echo ""

echo "=================================="
echo "If you see Redis errors:"
echo "  - Make sure KV is created in Vercel dashboard"
echo "  - Check KV_URL is set in env vars"
echo "  - Wait 1-2 minutes for KV to be ready"
echo "  - Redeploy: git push origin main"
echo "=================================="
